name: Release Helm Chart
on:
    workflow_call:
        inputs:
            # -----------------
            # System & Versions
            # -----------------
            osVariant:
                type: string
                default: "ubuntu-22.04"

            # ------------------
            # Helm Chart release
            # ------------------
            chartPath:
                type: string
                default: ""
            chartRepoSuffix:
                description: "Repository name suffix, can be a subdirectory. Example full URL with suffix: ghcr.io/riotkit-org/charts/pgbr:1.0.1"
                type: string
                default: "charts/"

jobs:
    release-chart:
        runs-on: ${{ inputs.osVariant }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Create version string
              id: version
              run: |
                  ref="${{ github.ref_name }}"
                  if [[ "$(git log -n 1 --pretty=%d HEAD)" != *"tag:"* ]]; then
                      ref="0.0-latest-${{ github.ref_name }}"
                  fi
                  echo "ref=${ref}"

            - name: Publish Helm Chart to the OCI registry
              uses: appany/helm-oci-chart-releaser@v0.3.0
              with:
                  name: ${{ github.event.repository.name }}
                  repository: ${{ github.event.org.login }}${{ inputs.chartRepoSuffix }}
                  tag: ${{ steps.version.outputs.ref }}
                  path: ${{ inputs.chartPath }}
                  registry: ghcr.io
                  registry_username: ${{ github.actor }}
                  registry_password: ${{ secrets.GITHUB_TOKEN }}
