name: Release Helm Chart
on:
    workflow_call:
        inputs:
            # -----------------
            # System & Versions
            # -----------------
            osVariant:
                type: string
                default: "ubuntu-22.04"
            helmVersion:
                type: string
                default: "v3.11.2"
            helmDocsVersion:
                type: string
                default: "v1.11.0"
            yqVersion:
                type: string
                default: "v4.32.2"

            # ------------------
            # Helm Chart release
            # ------------------
            chartPath:
                type: string
                default: ""
            chartRepoName:
                description: "Repository name e.g. org-name/charts"
                type: string
            chartName:
                type: string
                default: ""

            enableHelmDocs:
                description: "Enable helm-docs (https://github.com/norwoodj/helm-docs). Create README.md.gotmpl file to customize the template"
                type: boolean
                default: false

jobs:
    release-chart:
        runs-on: ${{ inputs.osVariant }}
        steps:
            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "${{ inputs.helmVersion }}"

            - name: Set up YQ
              run: |
                  curl -L -s https://github.com/mikefarah/yq/releases/download/${{ inputs.yqVersion }}/yq_linux_amd64 --output /usr/local/bin/yq
        
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Calculate facts
              id: facts
              # language=bash
              run: |
                  # ===================
                  # Chart version
                  # ===================
                  ref="${{ github.ref_name }}"
                  if [[ "$(git log -n 1 --pretty=%d HEAD)" != *"tag:"* ]]; then
                      ref="0.0-latest-${{ github.ref_name }}"
                  fi
                  if [[ -f ${{ inputs.chartPath }}/bin/get-chart-version ]]; then
                      chmod +x ${{ inputs.chartPath }}/bin/get-chart-version
                      ref=$(${{ inputs.chartPath }}/bin/get-chart-version)
                  fi
                  echo "ref=${ref}" >> $GITHUB_OUTPUT
                  
                  # ===================
                  # helm-docs
                  # ===================
                  if [[ -f "${{ inputs.chartPath }}/README.md.gotmpl" ]]; then
                      echo "docs=true" >> $GITHUB_OUTPUT
                  else
                      echo "docs=false" >> $GITHUB_OUTPUT 
                  fi
                  
                  # ===================
                  # Application version
                  # ===================
                  app_version="${ref}"
                  if [[ -f ${{ inputs.chartPath }}/bin/get-app-version ]]; then
                      chmod +x ${{ inputs.chartPath }}/bin/get-app-version
                      app_version=$(${{ inputs.chartPath }}/bin/get-app-version)
                  fi
                  echo "app_version=${app_version}" >> $GITHUB_OUTPUT
                  
                  # ====================================================================
                  # Repo name - adds "dev" subdirectory if that's a snapshot
                  # so the artifacthub.io will not show always snapshot as latest stable
                  # ====================================================================
                  repo_name="${{ inputs.chartRepoName }}"
                  if [[ "${ref}" == *"-latest-"* ]]; then
                      repo_name="${repo_name}/dev"
                  fi
                  echo "repo_name=${repo_name}" >> $GITHUB_OUTPUT

            - name: Modify Chart.yaml
              # language=bash
              run: |
                  set -x
                  yq e -i ".appVersion= \"${{ steps.facts.outputs.app_version }}\"" ${{ inputs.chartPath }}/Chart.yaml
                  yq e -i ".version= \"${{ steps.facts.outputs.ref }}\"" ${{ inputs.chartPath }}/Chart.yaml

            - name: Generate README.md
              if: ${{ (steps.facts.outputs.docs == 'true' || inputs.enableHelmDocs) && !startsWith(github.ref, 'refs/tags/v') }}
              # language=bash
              run: |
                  cd ${{ inputs.chartPath }}
                  docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:${{ inputs.helmDocsVersion }}
                  git config --global user.email "example@example.org"
                  git config --global user.name "Riotkit via Github Actions"
                  git add README.md
                  git commit -m "chore: Bump README.md by release pipeline (automatic) / Riotkit" || true
                  git push

            - name: Verify Helm syntax
              # language=bash
              run: "cd ${{ inputs.chartPath }} && helm lint ./ && helm template ./ --debug"

            - name: Publish Helm Chart to the OCI registry
              uses: appany/helm-oci-chart-releaser@v0.3.0
              with:
                  name: ${{ inputs.chartName || github.event.repository.name }}
                  repository: ${{ steps.facts.outputs.repo_name }}
                  tag: ${{ steps.facts.outputs.ref }}
                  path: ${{ inputs.chartPath }}
                  registry: ghcr.io
                  registry_username: ${{ github.actor }}
                  registry_password: ${{ secrets.GITHUB_TOKEN }}
