name: Release Helm Chart
on:
    workflow_call:
        inputs:
            # -----------------
            # System & Versions
            # -----------------
            osVariant:
                type: string
                default: "ubuntu-22.04"
            helmVersion:
                type: string
                default: "v3.11.2"

            # ------------------
            # Helm Chart release
            # ------------------
            chartPath:
                type: string
                default: ""
            chartRepoName:
                description: "Repository name e.g. org-name/charts"
                type: string
            chartName:
                type: string
                default: ""

jobs:
    release-chart:
        runs-on: ${{ inputs.osVariant }}
        steps:
            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "${{ inputs.helmVersion }}"
        
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Calculate facts
              id: facts
              run: |
                  # version
                  ref="${{ github.ref_name }}"
                  if [[ "$(git log -n 1 --pretty=%d HEAD)" != *"tag:"* ]]; then
                      ref="0.0-latest-${{ github.ref_name }}"
                  fi
                  echo "ref=${ref}" >> $GITHUB_OUTPUT

            - name: Verify Helm syntax
              shell: "cd ${{ inputs.chartPath } && helm lint ./ && helm template ./ --debug"

            - name: Publish Helm Chart to the OCI registry
              uses: appany/helm-oci-chart-releaser@v0.3.0
              with:
                  name: ${{ inputs.chartName || github.event.repository.name }}
                  repository: ${{ inputs.chartRepoName }}
                  tag: ${{ steps.facts.outputs.ref }}
                  path: ${{ inputs.chartPath }}
                  registry: ghcr.io
                  registry_username: ${{ github.actor }}
                  registry_password: ${{ secrets.GITHUB_TOKEN }}
